[project]
name = "hprotein-domains"
version = "0.1.0"
description = "Retrieves Human protein domains."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "toml>=0.10.2",
    "xlsxwriter>=3.2.0",
]
