name: few basic actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a simple command
        run: echo "The code has been pushed successfully!"
      - name: File structure check
        run: ls -la
        
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Markdown links check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
      - name: Echo completion
        run: echo "Markdown links check completed!"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: pip install uv

      - name: Add project root to Python path
        run: echo "PYTHONPATH=$(pwd):$PYTHONPATH" >> $GITHUB_ENV

      - name: Run Tests with uv
        run: uv run pytest